[package]
name = "kittzo"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "time"] }
axum = "0.8"
tower-http = { version = "0.6", features = ["fs", "set-header"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1", features = ["derive"] }
toml = "0.9"
rusty-money = { version = "0.5.0", features = ["serde"] }
rust_decimal = "1.43"
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio", "migrate", "time", "uuid"] }
uuid = { version = "1.26.1", features = ["serde", "v4"] }
time = { version = "0.3.55", features = ["serde", "std", "formatting"] }
async-trait = "0.1.92"
tray-icon = "0.24.2"
tao = "0.37.0"
image = { version = "0.25.10", default-features = false, features = ["png"] }
twilight-http = "0.16"
twilight-model = "0.16"
twilight-gateway = "0.16"
thiserror = "2.0.20"
tower = { version = "0.5.3", features = ["util"] }

[dev-dependencies]
mockall = "0.15.0"
serde_json = "1"

[build-dependencies]
winresource = "0.1.31"
